export const ALL_PRODUITS_REQUEST = "ALL_PRODUITS_REQUEST"

export const ALL_PRODUITS_SUCCESS = "ALL_PRODUITS_SUCCESS"

export const ALL_PRODUITS_FAIL = "ALL_PRODUITS_FAIL"

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const PRODUIT_DETAILS_REQUEST = "PRODUIT_DETAILS_REQUEST"

export const PRODUIT_DETAILS_SUCCESS = "PRODUIT_DETAILS_SUCCESS"

export const PRODUIT_DETAILS_FAIL = "PRODUIT_DETAILS_FAIL"
